### ISSUE TITLE
Add button on img2img to set width/height to that of the input image

### ISSUE THREAD

**Issue by thomasasfk** [thomasasfk/sd-webui-aspect-ratio-helper#14]
ControlNet has a button to do this, it would be cool to replicate it here as an option.

**Comment by NAS4Killer** [comment]
Hi, I have the Version "b03cce20 (Mon Apr 10 21:17:00 2023)". I cannot find a update.
But how work this function?
If I select the Frame/picture icon into the helper and put the image into img2img. Nothig is doing. I tray the render and I try the render with controlnet and pixelperfect. But The resolution not automatical configure. What I can do?

**Comment by thomasasfk** [comment]
> Hi, I have the Version "b03cce20 (Mon Apr 10 21:17:00 2023)". I cannot find a update. But how work this function? If I select the Frame/picture icon into the helper and put the image into img2img. Nothig is doing. I tray the render and I try the render with controlnet and pixelperfect. But The resolution not automatical configure. What I can do?

Hmm - so you select the frame 🖼 & add an image, but the aspect ratio/width & height don't adjust?

Which method are you using to add the image, ctrl + v, drag and drop, manual select via file explorer, etc?

**Comment by NAS4Killer** [comment]
Hi, thank for a fast answer. Yes correct so is it.
Normaly I use the german version and add the image by drag and drop. But I test today add the image by file explorer and the english version. But the same issue. The ratio, width&height not change.

what I found out now is the following.

If I choose "🔒" and one of the sliders turns gray and I then click "off" again, the slider becomes active again. As soon as I go back to the "🖼" afterwards. The slider then turns gray again.
