### ISSUE TITLE
Would love some common aspect ratios implemented as buttons

### ISSUE THREAD

**Issue by ilazarte** [thomasasfk/sd-webui-aspect-ratio-helper#23]
https://en.wikipedia.org/wiki/Aspect_ratio_(image)
film, photography (all kinds, including selfies) jump to the top of the list for me, but also maybe social targets (TT/Insta/YT) 
webui already has a button to switch hz-vertical so just a single type is needed.  

Some examples:
(6:13 Smartphone) (1.6180:1 Golden Ratio) (16:9 HD Broadcast)

**Comment by thomasasfk** [comment]
Hello! This has fortunately already been implemented.

If you update your extension you should be able to specify in the settings any aspect ratios you like. 

If it doesn't work at all, or you meant something else, please let me know!

**Comment by ilazarte** [comment]
Wow just saw it, thank you and thanks for your plugin!
