### ISSUE TITLE
not sync!!! (( JavaScript aspect ratio controls )) and [[ aspect ratio ]] tab is not sync!!! and tab has no way to disable :)

### ISSUE THREAD

**Issue by bryanray** [thomasasfk/sd-webui-aspect-ratio-helper#27]
not sync!!! (( JavaScript aspect ratio controls )) and [[ aspect ratio ]] tab is not sync!!! and tab has no way to disable :)

**Comment by thomasasfk** [comment]
Sorry, can you clarify what you mean by this?  Do you have a video at all?

**Comment by bryanray** [comment]
hi thanks, yes

( JavaScript aspect ratio controls )) and [[ aspect ratio ]] tab is not sync!!!
       ---> regarding this, with default setting, the "predefine buttons) are enabled, BUT, now i also enable (( JavaScript aspect ratio controls )), NOW, if I click pre-define button, the java would not sync. maybe i will just need to disable one of them,

and tab has no way to disable :)
       ---> by this i mean the menu, under the parameters, dont know what that parts of the ui called..... anyway, i managed to make it disapear by unchecking both "pre-defined" box....... so there no more UI conflict and look illogical.....

**Comment by bryanray** [comment]
and only one java button there, which is nice neatly tugged. there are not much vertical space in this over croweded space, there are controlnet, cut off, latent couple, composable lora, etc etc, EVERYONE is using this ui part....:)) LOL

**Comment by thomasasfk** [comment]
> and only one java button there, which is nice neatly tugged. there are not much vertical space in this over croweded space, there are controlnet, cut off, latent couple, composable lora, etc etc, EVERYONE is using this ui part....:)) LOL

Thank you!  That's a good point.  That was the idea behind the JavaScript functionality, as it's relatively small and doesn't contribute to the already overcrowding on the main pages!  In order to hide the accordion - you need to hide all the sub options, this may not be intuitive though - so I'll raise an issue to add an option that's more clear.

**Comment by bryanray** [comment]
thank you! 
oh thats called "accordion" i remember this now, from way back, wordpress time :))
