### ISSUE TITLE
request update

### ISSUE THREAD

**Issue by Chunbear** [thomasasfk/sd-webui-aspect-ratio-helper#30]
![image](https://user-images.githubusercontent.com/34836688/227728161-1c4863ef-14e2-4479-a3dd-7e8cf9d15b31.png)
webui has updated gradio 3.23, the UI interface has changed

**Comment by thomasasfk** [comment]
Thanks for raising, I'll take a look.

**Comment by thomasasfk** [comment]
Thanks again for raising, this is fixed in https://github.com/thomasasfk/sd-webui-aspect-ratio-helper/pull/31
