### ISSUE TITLE
a1111 webui's slider 8 incremental step wont work if [JavaScript aspect ratio controls] is activated

### ISSUE THREAD

**Issue by bryanray** [thomasasfk/sd-webui-aspect-ratio-helper#34]
commit: [a9fed7c3]

a1111 webui's slider 8 incremental step wont work if [JavaScript aspect ratio controls] is activated,

this perhaps is always the case :)

**Comment by bryanray** [comment]
javascript icons/ lengends are not centered as it should be usually, instead they are left aligned.

these two issues appears after latest update :))

**Comment by thomasasfk** [comment]
Hey!  The step was deliberately set to 1 so the aspect ratio could be as precise as possible. 

It's very easy to make configurable though, so I'll add an option for it when I have time.

https://github.com/thomasasfk/sd-webui-aspect-ratio-helper/blob/main/javascript/aspectRatioController.js#L79

In terms of the styling, it should be easy enough to center the text, I'll do that at the same time when I have time!

Thanks for raising.

**Comment by bryanray** [comment]
i wish i know how to code, then i can contribute to this plugin :) LOL

**Comment by bryanray** [comment]
> Hey! The step was deliberately set to 1 so the aspect ratio could be as precise as possible.
> 
> It's very easy to make configurable though, so I'll add an option for it when I have time.
> 
> https://github.com/thomasasfk/sd-webui-aspect-ratio-helper/blob/50cf127c44fc100e3e78b84f288cb07f6c7dc67e/javascript/aspectRatioController.js#L79
> 
> In terms of the styling, it should be easy enough to center the text, I'll do that at the same time as the other change!
> 
> Thanks for raising.



another really important thing is, 
the "off" options should have been off to make 8 incremental stepping on again, that would be great!

**Comment by thomasasfk** [comment]
https://github.com/thomasasfk/sd-webui-aspect-ratio-helper/issues/36#issuecomment-1492479473

**Comment by bryanray** [comment]
thanks dude :) 

amazing app you've done here
