### ISSUE TITLE
Feature Request: Setting option to show only lock button as On/Off (w/o the pull down + A/R list)

### ISSUE THREAD

**Issue by CCpt5** [thomasasfk/sd-webui-aspect-ratio-helper#44]
Hello,

Love the extension - thanks again for the time/effort.

I was curious if it'd ever be possible to add a setting option to make the java script button (by the height/width) be only the lock icon w/o the AR drop down. If enabled the button would just be a simple on/off for locking the height and width at the current setting. I know you can do that now if you open the pulldown and click the lock icon. However, sometimes I find myself mainly using the lock, and having it as a simple on/off (1 click) vs. click to open panel/selecting the lock icon on the list is maybe slightly less optimal. 

I know it's a minor nuance thing, but one feature I know I'd find helpful for certain times when I'm just playing around.  
  
One other thing that maybe I should have started a new thread for is that the red overlay in the IMG2IMG tab doesn't respond accurately when the height/width are locked and you adjust the resolution slider.  The slider you move adjusts the red overlay as it should, but the snapping of the other slider into proper AR does not move the red overlay which leaves it "out of sync" with the resolution setting. I know the red overlay has been buggy recently in general (it disappears at times), so maybe a fix for this isn't possible (or at this time).  Just wanted to mention though.

Thanks!

**Comment by thomasasfk** [comment]
Thanks for mentioning, it's much appreciated - I don't use stable diffusion all too often, so I rely on issues like these to know when things go wrong.  

In regards to your feature request, I've added this in: https://github.com/thomasasfk/sd-webui-aspect-ratio-helper/pull/45

If you update your extension, there should be a new setting "JavaScript selection method", you should be able to select "Default Options Button", which changes the original dropdown to a static button, when clicked it will cycle through the different default options, for txt2img this is just "Off" & "🔒", however for img2img it's "Off", "🔒" & "🖼"
