### ISSUE TITLE
On vladmandic's fork, swap button doesn't appear

### ISSUE THREAD

**Issue by brknsoul** [thomasasfk/sd-webui-aspect-ratio-helper#49]
I have the aspect ratio dropdown, but I don't see the Swap button.
![image](https://user-images.githubusercontent.com/1969381/234972024-602d193e-566b-4d63-b8b9-ef031b72e1cf.png)

**Comment by thomasasfk** [comment]
Hmm I didn't write this with vlads fork in mind.  If I find some time I'll see if I can look into it but been pretty busy lately, if anyone wants to contribute a pull request it's welcomed!

**Comment by thomasasfk** [comment]
I'll have some time this weekend (hopefully) so will see how difficult a fix is.

**Comment by brknsoul** [comment]
I'm gonna update this; The switch button is there now, but the AR lock dropdown is missing.
It's been like this for a few updates of Vladmandic's fork.

**Comment by thomasasfk** [comment]
> I'm gonna update this; The switch button is there now (looks like this isn't a part of this extension), but the AR lock dropdown is missing. It's been like this for a few updates of Vladmandic's fork.

Yep sorry, haven't had time to set up that fork and look into it.  I'll leave this open incase anyone else wants to give it a go at fixing it, but it may take me a while as I'm working on other things atm, sorry.

**Comment by brknsoul** [comment]
Note: Egg on face time;
Placing my extensions behind a symlink caused a lot of issues. Those issues vanished when I removed the symlink and copied the extension back to the main folder.

Closeable.
