### ISSUE TITLE
[Feature Request] toggle to edit minimum dimension

### ISSUE THREAD

**Issue by rjgoif** [thomasasfk/sd-webui-aspect-ratio-helper#51]
I usually want my smaller dimension to be _at least_ 512, and I lock image dimensions to the source. This is a bit of a pain when using images with different dimensions as source, as I have to adjust each time.

It would be nice if I could set the minimum dimension instead of the max, and the max would adjust accordingly. Maybe add a toggle to swap the editable dimension?

**Comment by thomasasfk** [comment]
Ah, this should be relatively simple to add - I'll try to get to it this weekend as I have some time, thanks for the recommendation, definitely a valid use-case.

**Comment by thomasasfk** [comment]
Hi, thanks for the suggestion.  

For now, I've added a new component which is the opposite of the existing one, you can enable it if you want to use it.

You can also disable the old one, if you don't use it.  Please let me know if this isn't sufficient, or you have another suggestion.

I think ideally these could be a single component and take up less UI space, and use the same slider... but that's more work - so maybe I'll do that in the future and deprecate the existing components.

Here is a vid example:

https://github.com/thomasasfk/sd-webui-aspect-ratio-helper/assets/22506439/be4c55f2-acea-4b28-946a-2207b633d226
