### ISSUE TITLE
I can't turn off the extension from the extensions tab in Auto1111

### ISSUE THREAD

**Issue by magekinnarus** [thomasasfk/sd-webui-aspect-ratio-helper#53]
![Aspect Helper 01](https://github.com/thomasasfk/sd-webui-aspect-ratio-helper/assets/114774918/fb574f4f-529f-4d7b-881a-3868ffa0a9ed)
It is quite handy to be able to calculate the dimensions. But by default, it takes up several lines of space in txt2img, img2img tabs. So, I want to toggle off the feature sometimes to make it easy to work on the other extensions. The problem is that even when I check off the extension in the extensions tab, it still shows up on all the tabs. Is there a way to turn it off?

**Comment by thomasasfk** [comment]
> It is quite handy to be able to calculate the dimensions. But by default, it takes up several lines of space in txt2img, img2img tabs. So, I want to toggle off the feature sometimes to make it easy to work on the other extensions. The problem is that even when I check off the extension in the extensions tab, it still shows up on all the tabs. Is there a way to turn it off?

Hi - I don't see the extension here on the screenshot you've provided, at least in the way you've described it.  

This small icon is coming from our extension ([sd-webui-aspect-ratio-helper](https://github.com/thomasasfk/sd-webui-aspect-ratio-helper)):
![image](https://github.com/thomasasfk/sd-webui-aspect-ratio-helper/assets/22506439/d80fdc0f-3a68-4b17-848e-a7d9db9af0cb)

However if the multiple lines you're referring to is this group of buttons:

![image](https://github.com/thomasasfk/sd-webui-aspect-ratio-helper/assets/22506439/643bc3c7-b902-475f-b237-7e5a49e78d0f)

They belong to [sd-webui-ar](https://github.com/alemelis/sd-webui-ar) I think, so you may need to toggle that off if you don't want them to appear!

Let me know if this helps or I've misunderstood.

**Comment by magekinnarus** [comment]
Thanks. It's a bit embarrassing that the problem wasn't related to your extension. Yes, I turned off sd-webui-ar and the problem was solved.
