### ISSUE TITLE
【FEATURE REQUEST】 About the image size over 2048pix

### ISSUE THREAD

**Issue by amimi818** [thomasasfk/sd-webui-aspect-ratio-helper#60]
I imported an image in ControlNet with image size over 2048 pixels (e.g. 4096*3072) and then used "Send demensions to SD" to pass the image size into SD.
At this point, if I use the "aspect-ratio" extension again, I cannot lock the aspect ratio of the image in SD according to the ratio of the ControlNet image.

Can you improve this extension to handle this case？

**Comment by jmilez** [comment]
I have the same issue.  My thought would be to add multipliers to the pop-up menu along with the ratios.  So if you added percents to the javascript popup menu such as 1:1, 3:2, 4:3, 5:4, 16:9, **50%, 200%**.  If the menu item has a colon, it's a ratio, if a % it's a scaling factor. Then I wouldn't even need to display the user interface accordion.

LOVE the extension! just happened to find it before suggesting the same feature to the main A1111!

**Comment by LuisBurdallo** [comment]
Any chance this can be solved? So it calculates the aspect ratio for anything above 2048? Right now it locks the max and min to the defaults even though I've changed the ui-config.json to allow me using higher dimensions.

**Comment by amimi818** [comment]
> I was looking for this issue and seems that nobody fixed it but it's quite simple so it calculates the aspect ratio for anything above 2048? Right now it locks the max and min to the defaults even though I've changed the ui-config.json to allow me using higher dimensions.
> 
> Go to stable-diffusion-webui\extensions\sd-webui-aspect-ratio-helper\javascript and open aspectRatioController.js change the max dimension to your desire.

thx.

**Comment by amimi818** [comment]
Go to stable-diffusion-webui\extensions\sd-webui-aspect-ratio-helper\javascript
and open aspectRatioController.js
change the max dimension to your desire.
